<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlg2iuK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlg2iuK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDlg2iuK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDlg2iuK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDlg2iuK\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dlg2iuK',
    'container.build_id' => '7f4695e4',
    'container.build_time' => 1596893730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlg2iuK');
